model_type: XGBClassifier
library: xgboost.sklearn
hyperparameters:
  objective: binary:logistic
  base_score: null
  booster: null
  callbacks: null
  colsample_bylevel: null
  colsample_bynode: null
  colsample_bytree: null
  device: null
  early_stopping_rounds: null
  enable_categorical: false
  eval_metric: auc
  feature_types: null
  feature_weights: null
  gamma: null
  grow_policy: null
  importance_type: null
  interaction_constraints: null
  learning_rate: 0.015
  max_bin: null
  max_cat_threshold: null
  max_cat_to_onehot: null
  max_delta_step: null
  max_depth: 3
  max_leaves: null
  min_child_weight: null
  missing: .nan
  monotone_constraints: null
  multi_strategy: null
  n_estimators: 400
  n_jobs: null
  num_parallel_tree: null
  random_state: 10
  reg_alpha: null
  reg_lambda: null
  sampling_method: null
  scale_pos_weight: 3
  subsample: null
  tree_method: null
  validate_parameters: null
  verbosity: null
threshold: 0.466
training_datetime: '2025-07-07 01:28:40'
